coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%
ignore:
  # This is an experimental approach, which should be extracted into a separate repository, so that it can
  #  be reused between frontend-app-learning, frontend-app-course-authoring and frontend-app-library-authoring.
  - src/courseware/course/sequence/XBlock/*
